Models/ErrorViewModel.cs
namespace LearningLanguagePlatform.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/User.cs
using Microsoft.AspNetCore.Identity;
using System.ComponentModel.DataAnnotations;

namespace LearningLanguagePlatform.Models
{
    public class User : IdentityUser
    {       
        [Required(ErrorMessage = "Name is required")]
        [StringLength(50)]
        [MaxLength(50)] 
        public string Name { get; set; }

       [Required]
        public string SelectedLanguage { get; set; }

        public string UserType { get; set; }
    }
}

ViewModels/LoginVM.cs
using System.ComponentModel.DataAnnotations;

namespace LearningLanguagePlatform.ViewModels
{
    public class LoginVM
    {
        [Required(ErrorMessage = "Email is required")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [Required(ErrorMessage = "Password is required")]
        [DataType (DataType.Password)]
        public string Password { get; set; }
    }
}

ViewModels/RegisterVM.cs
using System.ComponentModel.DataAnnotations;

namespace LearningLanguagePlatform.ViewModels
{
    public class RegisterVM
    {
        [Required(ErrorMessage = "Name is required")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Please Select the language which you want to learn.")]
        public string SelectLanguage { get; set; }

        [Required(ErrorMessage = "Email is required")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [Required(ErrorMessage = "Password is required")]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Compare("Password", ErrorMessage = "Password doesn't match!")]
        [DataType(DataType.Password)]
        public string ConfirmPassword { get; set; }
    }
}

Controllers/HomeController.cs
using LearningLanguagePlatform.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace LearningLanguagePlatform.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }
        public IActionResult WelcomePage()
        {
            return View();
        }

        public IActionResult LearningPage()
        {
            return View();
        }

        public IActionResult Dashboard()
        {
            return View();
        }

        public IActionResult ContactUs()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }
    }
}

Controllers/RegistrationAndLoginController.cs
using Microsoft.AspNetCore.Mvc;
using LearningLanguagePlatform.ViewModels;
using Microsoft.AspNetCore.Identity;
using LearningLanguagePlatform.Models;
using Microsoft.AspNetCore.Mvc.ModelBinding;

namespace LearningLanguagePlatform.Controllers
{
    public class RegistrationAndLoginController : Controller
    {
        private readonly SignInManager<User> signInManager;
        private readonly UserManager<User> userManager;

        public RegistrationAndLoginController(SignInManager<User> signInManager, UserManager<User> userManager)
        {
            this.signInManager = signInManager;
            this.userManager = userManager;
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> LoginAsync(LoginVM model)
        {
            if(ModelState.IsValid)
            {
                var result = await signInManager.PasswordSignInAsync(model.Email,model.Password!, false, lockoutOnFailure: false);
                if (result.Succeeded)
                {
                    return RedirectToAction("WelcomePage", "Home");
                }

                ModelState.AddModelError("", "Invalid login attempt");
                return View(model);
            }
            return View(model);
        }

        public IActionResult Registration()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Registration(RegisterVM model)
        {
            if (ModelState.IsValid)
            {
                User user = new()
                {
                    UserName = model.Email,
                    Name = model.Name,
                    SelectedLanguage = model.SelectLanguage,    
                    Email = model.Email,
                };

                var result = await userManager.CreateAsync(user, model.Password);

                if (result.Succeeded)
                {
                    if (user.Email == "ahmed@admin.com")
                    {
                        await userManager.AddToRoleAsync(user, "Admin");
                    }
                    else
                    {
                        await userManager.AddToRoleAsync(user, "User");
                    }

                    await signInManager.SignInAsync(user, false);
                    return RedirectToAction("Login", "RegistrationAndLogin");
                }
                foreach(var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }
            return View(model);
        }

        public async Task<IActionResult> Logout()
        {
            await signInManager.SignOutAsync();
            return RedirectToAction("Login", "RegistrationAndLogin");
        }
    }
}

Controllers/UserSelectionController.cs
using Microsoft.AspNetCore.Mvc;

namespace LearningLanguagePlatform.Controllers
{
    public class UserSelectionController : Controller
    {

        public IActionResult PurposeOflearning()
        {
            return View();
        }

        public IActionResult LanguageKnowledge()
        {
            return View();
        }
        
        public IActionResult DailyGoals()
        {
            return View();
        }

    }
}

Views/Home/ContactUs.cshtml
@{
    ViewData["Title"] = "ContactUs";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <div class="bg-white rounded-3 p-3">
                    <div class="mb-3">
                        <label for="name" class="form-label fs-5" style="color: #5125D2;">Name :</label>
                        <input type="text" class="form-control" id="name" placeholder="Enter your name">
                    </div>
                    <div class="mb-3">
                        <label for="email" class="form-label fs-5" style="color: #5125D2;">Email :</label>
                        <input type="email" class="form-control" id="email" placeholder="Enter your email">
                    </div>
                    <div class="mb-3">
                        <label for="subject" class="form-label fs-5" style="color: #5125D2;">Subject :</label>
                        <input type="text" class="form-control" id="subject" placeholder="Enter the subject">
                    </div>
                    <div class="mb-3">
                        <label for="course" class="form-label fs-5" style="color: #5125D2;">Course Name :</label>
                        <input type="text" class="form-control" id="course" placeholder="Enter the course name">
                    </div>
                    <div class="mb-3">
                        <label for="reason" class="form-label fs-5" style="color: #5125D2;">Detailed Reason :</label>
                        <textarea class="form-control" id="reason" rows="5" placeholder="Enter detailed reason"></textarea>
                    </div>
                    <div class="mb-3">
                        <button type="submit" class="btn btn-primary btn-lg w-100" style="background-color: #5125D2;">Submit</button>
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <img class="img-fluid rounded-3 height:400px" src="/images/Rectangle 79.png" alt="Placeholder image">
            </div>
        </div>
    </div>

</body>
</html>

Views/Home/LearningLanguageArabic.cshtml
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<User> signInManager

@{
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Learning Page</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
</head>
<body>
    @if (User.IsInRole("Admin"))
    {
        <h1> Hi Admin!!!</h1>
    }

    <div style="width: 1440px; height: 1157px; padding-top: 157px; padding-bottom: 239px; padding-left: 407px; padding-right: 406px; background: white; flex-direction: column; justify-content: flex-start; align-items: center; display: inline-flex">
        <div style="width: 627px; height: 1881px; position: relative; flex-direction: column; justify-content: flex-start; align-items: flex-start; display: flex">
            <div style="position: relative; left: 200px; bottom: 17px; color: black; font-size: 40px; font-family: Poppins; font-weight: 600; text-transform: capitalize; word-wrap: break-word">اكمل تعلم العربيه</div>
            <div style="width: 627px; height: 808px; position: relative">
                <div style="width: 201px;
            height: 42.32px;
            left: 20px;
            top: 14.11px; position: absolute; text-align: center; color: black; font-size: 30px; font-family: Poppins; font-weight: 600; text-transform: capitalize; word-wrap: break-word">
                    الدرس 1: التعريفات
                </div>
                <div style="width: 627px; height: 700px; left: 0px; top: 0px; position: absolute; border-radius: 20px; border: 1px #88889D solid"></div>
                <div style="width: 577px; height: 0px; left: 25px; top: 76.64px; position: absolute; border: 8px #88889D solid"></div>
                <div style="width: 74px; height: 0px; left: 25px; top: 76.64px; position: absolute; border: 8px #5125D2 solid"></div>
                <div style="width: 324px; height: 94.04px; left: 14px; top: 127.89px; position: absolute">
                    <div style="width: 77px; height: 36.67px; left: 113px; top: 11.69px; position: absolute; text-align: center; color: black; font-size: 26px; font-family: Poppins; font-weight: 500; text-transform: capitalize; word-wrap: break-word">مرحبا!!</div>
                    <div style="width: 211px; height: 28.21px; left: 70px; top: 54.03px; position: absolute; text-align: center; color: #88889D; font-size: 20px; font-family: Poppins; font-weight: 500; text-transform: capitalize; word-wrap: break-word">تعلم بعض التحيات</div>
                    <div style="width: 100px; height: 94.04px; left: 0px; top: 0px; position: absolute; border-radius: 9999px; border: 2px #5125D2 solid"></div>
                    <img style="width: 90px; height: 84.63px; left: 5px; top: 5.11px; position: absolute; border-radius: 9999px" src="https://via.placeholder.com/90x85" />
                </div>
                <div style="width: 30px; height: 30px; left: 49px; top: 202.12px; position: absolute; background: #5125D2; border-radius: 9999px"></div>
                <div style="width: 32px; height: 32px; padding: 3px; left: 48px; top: 201px; position: absolute; justify-content: center; align-items: center; display: inline-flex">
                    <div style="width: 26px; height: 26px; background: white"></div>
                </div>
                <div style="width: 37.06px; height: 0px; left: 64px; top: 230px; position: absolute; transform: rotate(90deg); transform-origin: 0 0; border: 2px #5125D2 solid"></div>
                <div style="width: 100px; height: 94.04px; left: 14px; top: 267.06px; position: absolute; border-radius: 9999px; border: 2px #5125D2 solid"></div>
                <div style="width: 471px; height: 84.63px; left: 19px; top: 271.76px; position: absolute">
                    <div style="width: 201px; height: 36.67px; left: 75px; top: 7.52px; position: absolute; text-align: center; color: black; font-size: 26px; font-family: Poppins; font-weight: 500; text-transform: capitalize; word-wrap: break-word">تعلم قول اسمك</div>
                    <div style="width: 150px; height: 28.21px; left: 108px; top: 49.84px; position: absolute; text-align: center; color: #88889D; font-size: 20px; font-family: Poppins; font-weight: 500; text-transform: capitalize; word-wrap: break-word">حيا الناس وقول اسمك</div>
                    <img style="width: 90px; height: 84.63px; left: 0px; top: 0px; position: absolute; border-radius: 9999px" src="https://via.placeholder.com/90x85" />
                </div>
                <div style="width: 30px; height: 30px; left: 49px; top: 341.29px; position: absolute; background: #5125D2; border-radius: 9999px"></div>
                <div style="width: 32px; height: 32px; padding: 3px; left: 48px; top: 340px; position: absolute; justify-content: center; align-items: center; display: inline-flex">
                    <div style="width: 26px; height: 26px; background: white"></div>
                </div>
                <div style="width: 37px; height: 0px; left: 63px; top: 369px; position: absolute; transform: rotate(90deg); transform-origin: 0 0; border: 2px #5125D2 solid"></div>
                <div style="width: 310px; height: 36.67px; left: 127px; top: 554px; position: absolute; color: black; font-size: 26px; font-family: Poppins; font-weight: 500; text-transform: capitalize; word-wrap: break-word">ماذا تعلمت</div>
                <div style="left: 127px; top: 593.54px; position: absolute; text-align: center; color: #88889D; font-size: 20px; font-family: Poppins; font-weight: 500; text-transform: capitalize; word-wrap: break-word">اختبر مهاراتك للوصول إلى الدرس التالي</div>
                <div style="width: 487px; height: 94.04px; left: 14px; top: 406.23px; position: absolute">
                    <div style="width: 310px; height: 36.67px; left: 10px; top: 12.22px; position: absolute; text-align: center; color: black; font-size: 26px; font-family: Poppins; font-weight: 500; text-transform: capitalize; word-wrap: break-word">القاء التحياه</div>
                    <div style="width: 374px; height: 28.21px; left: 25px; top: 54.54px; position: absolute; text-align: center; color: #88889D; font-size: 20px; font-family: Poppins; font-weight: 500; text-transform: capitalize; word-wrap: break-word">تعلم كيف تسال عن احول الناس</div>
                    <div style="width: 100px; height: 94.04px; left: 0px; top: 0px; position: absolute; border-radius: 9999px; border: 2px #88889D solid"></div>
                    <img style="width: 90px; height: 84.63px; left: 5px; top: 4.70px; position: absolute; border-radius: 9999px" src="https://via.placeholder.com/90x85" />
                </div>
                <div style="width: 45.14px; height: 0px; left: 63px; top: 500.27px; position: absolute; transform: rotate(90deg); transform-origin: 0 0; border: 2px #88889D solid"></div>
                <div style="width: 100px; height: 94.04px; left: 14px; top: 544.23px; position: absolute; border-radius: 9999px; border: 2px #88889D solid"></div>
                <div style="width: 30px; height: 28.21px; left: 49px; top: 615.46px; position: absolute; border-radius: 9999px"></div>
                <img style="width: 90px; height: 85px; left: 19px; top: 549px; position: absolute; border-radius: 40px;" src="https://via.placeholder.com/90x85" />
            </div>

</body>
</html>

Views/Home/WelcomePage.cshtml
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<User> signInManager;
@model System.Security.Claims.ClaimsPrincipal

@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <style>
        body,
        html {
            height: 100%;
            margin: 0;
            padding: 0;
        }

        .bg-custom {
            background-color: #5125d2;
            height: 100%;
        }


    </style>
</head>

<body>
    @if (signInManager.IsSignedIn(User))
    {
        <div class="container-fluid h-100 bg-custom position-relative">
            <div class="row h-100 align-items-center">
                <div class="col-md-6 offset-md-3 text-center">
                    <img src="~/images/rocket.png" class="img-fluid mb-5" style="width: 338px; height: 338px;">
                    <h1 class="text-white fw-bold fs-1">Welcome @User.Identity.Name at the LLP.</h1>
                    <h2 class="text-white fw-bold fs-3 mt-3">Let’s do this.</h2>
                    <div class="mt-5">
                        <button class="btn btn-outline-dark btn-lg" style="width: 320px;">
                            <a asp-action="LearningPage" asp-controller="Home" style="text-decoration: none; color: white;">
                                Start Lesson
                            </a>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    }
</body>

</html>

Views/UserSelection/DailyGoals.cshtml
@{
    Layout = null;
}

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

<div class="container">
    <div class="row justify-content-center">
        <div class="col-12 text-center mt-5">
            <img src="~/images/Logo.png" alt="Logo" width="99" height="74">
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-12 text-center mt-4">
            <h1 class="fw-bold">Set a daily study goal!</h1>
        </div>
    </div>
    <div class="text-center mb-4">
        <p style="color: #88889D; font-size: 15px">Create a learning habit to improve your Spanish.</p>
    </div>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card mb-3">
                    <div class="card-body">
                        <h5 class="card-title">5 minutes / day</h5>
                        <p class="card-text">Casual</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card mb-3">
                    <div class="card-body">
                        <h5 class="card-title">10 minutes / day</h5>
                        <p class="card-text">Regular</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card mb-3">
                    <div class="card-body">
                        <h5 class="card-title">15 minutes / day</h5>
                        <p class="card-text">Serious</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card mb-3">
                    <div class="card-body">
                        <h5 class="card-title">20 minutes / day</h5>
                        <p class="card-text">Intense</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="mb-4 d-flex justify-content-center">
        <a asp-controller="UserSelection" asp-action="WelcomePage">
            <button class="btn btn-lg btn-block" style="background-color: #EEE9FB; color: #5125D2; width: 348px; font-weight:bold;">Commit to daily Goal</button>
        </a>
    </div>
</div>

Views/UserSelection/LanguageKnowledge.cshtml
@{
    Layout = null;
}

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

<div class="container-fluid bg-white">
    <div class="row justify-content-center">
        <div class="col-12 text-center mt-5">
            <img src="~/images/Logo.png" alt="Logo" width="99" height="74">
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-12 text-center mt-4">
            <h1 class="fs-1 fw-bold">Tell Us about you!</h1>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-12 text-center mt-3">
            <h2 class="fs-1 fw-bold">How much Spanish do you know?</h2>
        </div>
    </div>
    <div class="text-center mb-4">
        <p style="color: #88889D; font-size: 20px">Learn what you need to travel with confidence.</p>
    </div>
    <div class="row justify-content-center mb-5">
        <div class="col d-flex justify-content-center">
            <div class="card text-center" style="width: 310px;">
                <div class="card-body">
                    <img src="~/images/finish-flag.png" alt="I’m a Beginner" class="mt-3">
                    <h5 class="card-title fs-4 fw-bold">I’m a Beginner</h5>
                    <p class="card-text fs-5" style="color: #88889D;">Start with the basics</p>
                </div>
            </div>
        </div>
        <div class="col d-flex justify-content-center">
            <div class="card text-center" style="width: 310px;">
                <div class="card-body">
                    <img src="~/images/book.png" alt="I know Some Spanish" class="mt-3">
                    <h5 class="card-title fs-4 fw-bold">I know Some Spanish</h5>
                    <p class="card-text fs-5" style="color: #88889D;">Find Your Level</p>
                </div>
            </div>
        </div>
    </div>
    <div class="mb-4 d-flex justify-content-center">
        <a asp-controller="UserSelection" asp-action="DailyGoals">
            <button class="btn btn-lg btn-block" style="background-color: #EEE9FB; color: #5125D2; width: 348px; font-weight:bold;">Continue</button>
        </a>
    </div>
</div>

Views/UserSelection/PurposeOfLearning.cshtml
@{
    Layout = null;
}

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

<div class="container-fluid bg-white">
    <div class="row justify-content-center">
        <div class="col-12 text-center mt-5">
            <img src="~/images/Logo.png" alt="Logo" width="99" height="74">
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-12 text-center mt-4">
            <h1 class="fs-1 fw-bold">Tell Us about you!</h1>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-12 text-center mt-3">
            <span class="fs-2 fw-bold">Hi </span><span class="text-primary fs-2 fw-bold">AMS</span><span class="fs-2 fw-bold">, Why are you learning Spanish?</span>
        </div>
    </div>
    <div class="text-center mb-4">
        <p style="color: #88889D; font-size: 20px">Assistance in personalising your path to learning.</p>
    </div>
    <div class="row justify-content-center mt-4">
        <div class="col-4 col-md-3 col-lg-2 mb-5">
            <div class="card text-center">
                <img src="~/images/job.png" alt="Work" class="card-img-top" style="width: 150px;">
                <div class="card-body">
                    <h5 class="card-title">Work</h5>
                </div>
            </div>
        </div>
        <div class="col-4 col-md-3 col-lg-2 mb-5">
            <div class="card text-center">
                <img src="~/images/school.png" alt="School" class="card-img-top" style="width: 150px;">
                <div class="card-body">
                    <h5 class="card-title">School</h5>
                </div>
            </div>
        </div>
        <div class="col-4 col-md-3 col-lg-2 mb-5">
            <div class="card text-center">
                <img src="~/images/travel.png" alt="Travel" class="card-img-top" style="width: 150px;">
                <div class="card-body">
                    <h5 class="card-title">Travel</h5>
                </div>
            </div>
        </div>
        <div class="col-4 col-md-3 col-lg-2 mb-5">
            <div class="card text-center">
                <img src="~/images/culture.png" alt="Culture" class="card-img-top" style="width: 150px;">
                <div class="card-body">
                    <h5 class="card-title">Culture</h5>
                </div>
            </div>
        </div>
    </div>
    <div class="row justify-content-center mt-4">
        <div class="col-4 col-md-3 col-lg-2 mb-5">
            <div class="card text-center">
                <img src="~/images/family.png" alt="Family & Community" class="card-img-top" style="width: 150px;">
                <div class="card-body">
                    <h5 class="card-title">Family & Community</h5>
                </div>
            </div>
        </div>
        <div class="col-4 col-md-3 col-lg-2 mb-5">
            <div class="card text-center">
                <img src="~/images/challengeMyself.png" alt="Challenge Myself" class="card-img-top" style="width: 150px;">
                <div class="card-body">
                    <h5 class="card-title">Challenge Myself</h5>
                </div>
            </div>
        </div>
        <div class="col-4 col-md-3 col-lg-2 mb-5">
            <div class="card text-center">
                <img src="~/images/others.png" alt="Other" class="card-img-top" style="width: 150px;">
                <div class="card-body">
                    <h5 class="card-title">Other</h5>
                </div>
            </div>
        </div>
    </div>
    <div class="mb-4 d-flex justify-content-center">
        <a asp-controller="UserSelection" asp-action="LanguageKnowledge">
            <button class="btn btn-lg btn-block" style="background-color: #EEE9FB; color: #5125D2; width: 348px; font-weight:bold;">Continue</button>
        </a>
    </div>
</div>

Views/UserSelection/SelectLanguage.cshtml
@{
    Layout = null;
}

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

<div class="container-fluid bg-white">
    <div class="row justify-content-center">
        <div class="col-12 text-center mt-5">
            <img src="~/images/Logo.png" alt="Logo" width="99" height="74">
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-12 text-center mt-4">
            <h1 class="fs-1 fw-bold">What would you like to learn</h1>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-6 col-md-4 col-lg-3 mb-5">
            <div class="card">
                <div class="card-body text-center">
                    <img src="~/images/flags/english.png" alt="English" class="mb-3">
                    <h2 class="fs-5">English</h2>
                </div>
            </div>
        </div>
        <div class="col-6 col-md-4 col-lg-3 mb-5">
            <div class="card">
                <div class="card-body text-center">
                    <img src="~/images/flags/spanish.png" alt="Spanish" class="mb-3">
                    <h2 class="fs-5">Spanish</h2>
                </div>
            </div>
        </div>
        <div class="col-6 col-md-4 col-lg-3 mb-5">
            <div class="card">
                <div class="card-body text-center">
                    <img src="~/images/flags/arabic.png" alt="Arabic" class="mb-3">
                    <h2 class="fs-5">Arabic</h2>
                </div>
            </div>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-6 col-md-4 col-lg-3 mb-5">
            <div class="card">
                <div class="card-body text-center">
                    <img src="~/images/flags/russian.png" alt="Russian" class="mb-3">
                    <h2 class="fs-5">Russian</h2>
                </div>
            </div>
        </div>
        <div class="col-6 col-md-4 col-lg-3 mb-5">
            <div class="card">
                <div class="card-body text-center">
                    <img src="~/images/flags/chinese.png" alt="Chinese" class="mb-3">
                    <h2 class="fs-5">Chinese</h2>
                </div>
            </div>
        </div>
        <div class="col-6 col-md-4 col-lg-3 mb-5">
            <div class="card">
                <div class="card-body text-center">
                    <img src="~/images/flags/france.png" alt="French" class="mb-3">
                    <h2 class="fs-5">French</h2>
                </div>
            </div>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-6 col-md-4 col-lg-3 mb-5">
            <div class="card">
                <div class="card-body text-center">
                    <img src="~/images/flags/italian.png" alt="Italian" class="mb-3">
                    <h2 class="fs-5">Italian</h2>
                </div>
            </div>
        </div>
        <div class="col-6 col-md-4 col-lg-3 mb-5">
            <div class="card">
                <div class="card-body text-center">
                    <img src="~/images/flags/japan.png" alt="Japanese" class="mb-3">
                    <h2 class="fs-5">Japanese</h2>
                </div>
            </div>
        </div>
        <div class="col-6 col-md-4 col-lg-3 mb-5">
            <div class="card">
                <div class="card-body text-center">
                    <img src="~/images/flags/korean.png" alt="Korean" class="mb-3">
                    <h2 class="fs-5">Korean</h2>
                </div>
            </div>
        </div>
    </div>
    <div class="mb-4 d-flex justify-content-center">
        <a asp-controller="UserSelection" asp-action="PurposeOfLearning">
            <button class="btn btn-lg btn-block" style="background-color: #EEE9FB; color: #5125D2; width: 348px; font-weight:bold;">Continue</button>
        </a>
    </div>

</div>